# All SpaceVim option below [option] section
[options]
    bootstrap_before = 'shaficustom#before'
    bootstrap_after = 'shaficustom#after'
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    colorscheme = 'nord'
    colorscheme_bg = 'dark'
    enable_guicolors = false
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    guifont = "Cascadia Code"
    default_indent = 4
    expand_tab = false
    enable_neomake = false
    enable_ale = false
    filemanager = "nerdtree"
    filetree_direction = 'left'
    filetree_show_hidden = true

[[custom_plugins]]
  repo = "arcticicestudio/nord-vim"
  merged = false

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

# Enable autocomplete layer
# [[layers]]
#     name = 'autocomplete'
#     autocomplete_method = 'ycm'
#     auto_completion_return_key_behavior = 'complete'
#     auto_completion_tab_key_behavior = 'smart'
# 	auto_completion_delay = 1000

[[layers]]
	name = 'checkers'
	lint_on_save = false


[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = "colorscheme"
    random_theme = false

[[layers]]
    name = 'fiemanager'

[[layers]]
    name = 'lang#python'
    filetypes = ["python"]

[[layers]]
	name = 'git'
    enable = true

[[layers]]
	name = 'VersionControl'

[[layers]]
	name = 'ui'

[[layers]]
	name = 'tmux'

[[layers]]
	name = 'lang#sh'

[[layers]]
	name = 'lang#latex'
